defaults: &defaults
 
:development:
  :couchdb:
    :url: http://localhost:5984/worddit
  <<: *defaults
  
:test:
  :couchdb:
    :url: http://localhost:5984/worddit
    <<: *defaults

:production:
  :couchdb:
    :url: http://localhost:5984/worddit
    <<: *defaults